import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import type { Plugin } from "vite";

export interface ServerConfig {
  /** Target runtime. Auto-detected at startup; detected runtime wins if both are set. */
  runtime?: "bun" | "node" | "vercel" | "cloudflare" | "netlify";
  /** TCP port for standalone servers (bun/node). Default 3000. */
  port?: number;
  /** Enable gzip/br compression (bun/node only). Default true. */
  compress?: boolean;
  /** Path to static assets directory, relative to CWD. Default './dist/client'. */
  static?: string;
}

/**
 * Vite plugin that serialises server config into the SSR output bundle.
 * Dev mode: no-op (entry-server.tsx + @hono/vite-dev-server handle everything).
 * SSR build: writes `dist/server/server-config.mjs` on `buildEnd`.
 */
export default function webRuntime(config: ServerConfig): Plugin {
  let configRoot: string;
  let isSSR = false;

  return {
    name: "web-runtime",

    configResolved(resolved) {
      configRoot = resolved.root;
      // Detect whether this is the SSR build pass
      isSSR = !!resolved.build?.ssr;
    },

    buildEnd() {
      // Only emit for the SSR build; client build has no use for this file.
      if (!isSSR) return;

      const outDir = resolve(configRoot, "dist", "server");
      if (!existsSync(outDir)) {
        mkdirSync(outDir, { recursive: true });
      }

      const content = `// Auto-generated by @consolidados/hono-vite-runtime — do not edit\nexport default ${JSON.stringify(config, null, 2)};\n`;
      writeFileSync(resolve(outDir, "server-config.mjs"), content, "utf-8");
      console.log("[web-runtime] Wrote dist/server/server-config.mjs");
    },
  };
}
